version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://server:8080

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - GIN_MODE=debug
      - PAYMENTS_SERVER_PORT=8080
      - PAYMENTS_PORTONE_BASE_URL=https://api.iamport.kr



networks:
  app-network:
    driver: bridge

# volumes:
#   db-data: 